// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iunhiovfssonlwthmeeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1bmhpb3Zmc3Nvbmx3dGhtZWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MjM3MjEsImV4cCI6MjA3NDE5OTcyMX0.1NKqY6DJ3T7pudVu4LkJSbcXrkk_O312FdNeWGZmnsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});